trend =  [
    ["rbs_x","http://127.0.0.1:22000/api/latest", "motor_1_position"],
    ["rbs_y","http://127.0.0.1:22000/api/latest", "motor_2_position"],
    ["rbs_phi","http://127.0.0.1:22001/api/latest", "motor_1_position"],
    ["rbs_zeta","http://127.0.0.1:22001/api/latest", "motor_2_position"],
    ["rbs_current","http://127.0.0.1:22100/api/latest", "current(nA)"],
    ["any_sf6_pressure","http://127.0.0.1:22101/api/latest", "counter_0_value"],
    ["any_sf6_temperature","http://127.0.0.1:22101/api/latest", "counter_1_value"],
    ["erd_ad1_count_rate","http://169.254.155.94:25000/api/latest", "ad1.total_rate"],
    ["erd_ad2_count_rate","http://169.254.155.94:25000/api/latest", "ad2.total_rate"],
    ["erd_z","http://127.0.0.1:22124/api/latest", "motor_position"],
    ["erd_theta","http://127.0.0.1:22123/api/latest", "motor_position"],
]
