[generic.hardware.aml_x_y]
type="aml"
title="AML X Y"
url="http://localhost:22000/api/latest"
names = ["X", "Y"]
loads = [110,20]

[generic.hardware.aml_det_theta]
type = "aml"
title = "AML Detector Theta"
url = "http://localhost:22000/api/latest"
names = ["Detector", "Theta"]
loads = [170, 10]

[generic.hardware.aml_phi_zeta]
type = "aml"
title = "AML Phi Zeta"
url = "http://localhost:22000/api/latest"
names = ["Phi", "Zeta"]
loads = [0, -1]

[generic.hardware.motrona_rbs]
type = "motrona"
title = "Motrona RBS"
url = "http://localhost:22100/api/latest"

[generic.hardware.caen_rbs]
type = "caen"
title = "Caen RBS"
url = "http://localhost:22200/api/latest"

[generic.hardware.mdrive]
type = "mdrive"
title = "MDrive"
url = "http://localhost:22300/api/latest"

[erd.hardware]
mdrive = "mdrive"

[rbs.hardware]
aml_x_y = "aml_x_y"
aml_phi_zeta = "aml_phi_zeta"
aml_det_theta = "aml_det_theta"
caen = "caen_rbs"
motrona = "motrona_rbs"

[rbs.folder_scan]
watch = "/tmp/ACQ/1_watch"
ongoing.local = "/tmp/ACQ/2_ongoing"
ongoing.remote = "/tmp/ACQ/REM/2_ongoing"
failed.local = "/tmp/ACQ/3_failed"
failed.remote = "/tmp/ACQ/REM/3_failed"
done.local = "/tmp/ACQ/4_done"
done.remote = "/tmp/ACQ/REM/4_done"

[rbs.data_dir]
local = "/tmp/ACQ/5_data"
remote = "/tmp/ACQ/REM/_05_data"
