[any.hardware.aml_u_v]
type="aml"
title="AML U V"
url="http://localhost:30000/api/latest"
names = ["U", "V"]
loads = [110,20]

[rbs.hardware.aml_x_y]
type="aml"
title="AML X Y"
url="http://localhost:30000/api/latest"
names = ["X", "Y"]
loads = [110,20]

[rbs.hardware.aml_det_theta]
type = "aml"
title = "AML Detector Theta"
url = "http://localhost:20000/api/latest"
names = ["Detector", "Theta"]
loads = [170, 10]

[rbs.hardware.aml_phi_zeta]
type = "aml"
title = "AML Phi Zeta"
url = "http://localhost:20000/api/latest"
names = ["Phi", "Zeta"]
loads = [0, -1]

[rbs.hardware.motrona]
type = "motrona"
title = "Motrona"
url = "http://localhost:20100/api/latest"

[rbs.hardware.caen]
type = "caen"
title = "Caen"
url = "http://localhost:20200/api/latest"

[erd.hardware.mdrive_z]
type = "mdrive"
title = "MDrive Z"
url = "http://localhost:22300/api/latest"

[erd.hardware.mdrive_theta]
type = "mdrive"
title = "MDrive Theta"
url = "http://localhost:22301/api/latest"

[erd.hardware.mpa3]
type = "mpa3"
title = "MPA 3"
url = "http://localhost:22301/api/latest"

[rbs.folder_scan]
watch = "/tmp/ACQ/1_watch"
ongoing.local = "/tmp/ACQ/2_ongoing"
ongoing.remote = "/tmp/ACQ/REM/2_ongoing"
failed.local = "/tmp/ACQ/3_failed"
failed.remote = "/tmp/ACQ/REM/3_failed"
done.local = "/tmp/ACQ/4_done"
done.remote = "/tmp/ACQ/REM/4_done"

[rbs.data_dir]
local = "/tmp/ACQ/5_data"
remote = "/tmp/ACQ/REM/_05_data"
