[any.hardware]

[rbs.hardware.aml_x_y]
type="aml"
title="AML X Y"
url="http://127.0.0.1:22000/api/latest"
names = ["X", "Y"]
loads = [72.5,61.7]

[rbs.hardware.aml_phi_zeta]
type = "aml"
title = "AML Phi Zeta"
url = "http://127.0.0.1:22001/api/latest"
names = ["Phi", "Zeta"]
loads = [0, -1]

[rbs.hardware.aml_det_theta]
type = "aml"
title = "AML Detector Theta"
url = "http://127.0.0.1:22002/api/latest"
names = ["Detector", "Theta"]
loads = [170.0, -180.5]

[rbs.hardware.motrona]
type = "motrona"
title = "Motrona"
url = "http://127.0.0.1:22100/api/latest"

[rbs.hardware.caen]
type = "caen"
title = "Caen"
url = "http://169.254.80.218:22200/api/latest"

[erd.hardware.mdrive_z]
type = "mdrive"
title = "MDrive Z"
url = "http://169.254.100.229:22124/api/latest"

[erd.hardware.mdrive_theta]
type = "mdrive"
title = "MDrive Theta"
url = "http://169.254.100.229:22123/api/latest"

[erd.hardware.mpa3]
type = "mpa3"
title = "MPA 3"
url = "http://169.254.155.94:25000/api/latest"

[rbs.data_dir]
local = "/mnt/mcaiba_nas/transfer_RBS"
remote = "/mnt/winbe_wasp/transfer_RBS"

[erd.data_dir]
local = "/mnt/mcaiba_nas/transfer_ERD/tst"
remote = "/mnt/winbe_wasp/transfer_ERD/tst"
