[generic.hardware.aml_x_y]
type="aml"
title="AML X Y"
url="http://localhost:22000/api/latest"
names = ["X", "Y"]
loads = [72.5,61.7]

[generic.hardware.aml_phi_zeta]
type = "aml"
title = "AML Phi Zeta"
url = "http://localhost:22001/api/latest"
names = ["Phi", "Zeta"]
loads = [0, -1]

[generic.hardware.aml_det_theta]
type = "aml"
title = "AML Detector Theta"
url = "http://localhost:22002/api/latest"
names = ["Detector", "Theta"]
loads = [170, -180.5]

[generic.hardware.motrona_rbs]
type = "motrona"
title = "Motrona RBS"
url = "http://localhost:22100/api/latest"

[generic.hardware.caen_rbs]
type = "caen"
title = "Caen RBS"
url = "http://169.254.80.218:22200/api/latest"

[generic.hardware.mdrive]
type = "mdrive"
title = "MDrive"
url = "http://localhost:22300/api/latest"

[erd.hardware]
mdrive = "mdrive"

[rbs.hardware]
aml_x_y = "aml_x_y"
aml_phi_zeta = "aml_phi_zeta"
aml_det_theta = "aml_det_theta"
caen = "caen_rbs"
motrona = "motrona_rbs"

[rbs.data_dir]
local = "/mnt/mcaiba_nas/transfer_RBS"
remote = "/mnt/winbe_wasp/transfer_RBS"

