[hw_control]
    [hw_control.aml_x_y]
    type = "aml"
    url = "http://localhost:22000/api/latest"
    names = ["X", "Y"]
    loads = [72.5, 61.7]
    title = "AML X Y"

    [hw_control.aml_det_theta]
    type = "aml"
    url = "http://localhost:22001/api/latest"
    names = ["Detector", "Theta"]
    loads = [170, -180.5]
    title = "AML Detector Theta"

    [hw_control.aml_phi_zeta]
    type = "aml"
    url = "http://localhost:22002/api/latest"
    names = ["Phi", "Zeta"]
    loads = [0, -1]
    title = "AML Phi Zeta"

    [hw_control.motrona_rbs]
    type = "motrona"
    url = "http://localhost:23000/api/latest"
    title = "Motrona RBS"

    [hw_control.caen_rbs]
    type = "caen"
    url = "http://169.254.80.218:22300/api/latest"
    title = "Caen RBS"

[rbs]
    [rbs.input_dir]
    watch = "/mnt/mcaiba_nas/1_watch"

    [rbs.output_dir]
    ongoing = "/mnt/mcaiba_nas/2_ongoing"
    done = "/mnt/mcaiba_nas/3_done"
    failed = "/mnt/mcaiba_nas/4_failed"
    data = "/mnt/mcaiba_nas/5_data"

    [rbs.remote_output_dir]
    ongoing = "/mnt/winbe_wasp/_02_ongoing"
    done = "/mnt/winbe_wasp/_03_done"
    failed = "/mnt/winbe_wasp/_04_failed"
    data = "/mnt/winbe_wasp/_05_data"
