[any.hardware.motrona_sf6]
type="motrona_ax350"
title="Motrona SF6"
url="http://127.0.0.1:22101/api/latest"
trend = {"pressure"="counter_0_value", "temperature"="counter_1_value"}

[rbs.hardware.aml_x_y]
type="aml"
title="AML X Y"
url="http://127.0.0.1:22000/api/latest"
names = ["X", "Y"]
loads = [72.5,61.7]
trend = {"rbs_x"="motor_1_position", "rbs_y"="motor_2_position"}

[rbs.hardware.aml_phi_zeta]
type = "aml"
title = "AML Phi Zeta"
url = "http://127.0.0.1:22001/api/latest"
names = ["Phi", "Zeta"]
loads = [0, -1]
trend = {"rbs_phi"="motor_1_position", "rbs_zeta"="motor_2_position"}

[rbs.hardware.aml_det_theta]
type = "aml"
title = "AML Detector Theta"
url = "http://127.0.0.1:22002/api/latest"
names = ["Detector", "Theta"]
loads = [170.0, -180.5]

[rbs.hardware.motrona_charge]
type = "motrona"
title = "Motrona"
url = "http://127.0.0.1:22100/api/latest"
trend = {"rbs_current"="current(nA)"}

[rbs.hardware.caen]
type = "caen"
title = "Caen"
url = "http://169.254.80.218:22200/api/latest"

[erd.hardware.mdrive_z]
type = "mdrive"
title = "MDrive Z"
load = -180
url = "http://127.0.0.1:22124/api/latest"
trend = {"erd_z"="motor_position"}

[erd.hardware.mdrive_theta]
type = "mdrive"
title = "MDrive Theta"
load = 90
url = "http://127.0.0.1:22123/api/latest"
trend = {"erd_theta"="motor_position"}

[erd.hardware.mpa3]
type = "mpa3"
title = "MPA 3"
url = "http://169.254.155.94:25000/api/latest"
trend = {"erd_ad1_count_rate"= "ad1.total_rate", "erd_ad2_count_rate"= "ad2.total_rate"}

[rbs.data_dir]
local = "/mnt/mcaiba_nas/transfer_RBS"
remote = "/mnt/winbe_wasp/transfer_RBS"

[erd.data_dir]
local = "/mnt/mcaiba_nas/transfer_ERD"
remote = "/mnt/winbe_wasp/transfer_ERD"
