[any.hardware.motrona_sf6]
type="motrona_ax350"
title="Motrona SF6"
url="http://127.0.0.1:22101/api/latest"

#[any.hardware.mirion_g64_radiation]
#type="mirion_g64"
#title="Mirion G64 Radiation"
#url="http://169.254.166.218:22300/api/latest"

[rbs.hardware.aml_x_y]
type="aml"
title="AML X Y"
url="http://127.0.0.1:22000/api/latest"
names = ["X", "Y"]

[rbs.hardware.aml_phi_zeta]
type = "aml"
title = "AML Phi Zeta"
url = "http://127.0.0.1:22001/api/latest"
names = ["Phi", "Zeta"]

[rbs.hardware.aml_det_theta]
type = "aml"
title = "AML Detector Theta"
url = "http://127.0.0.1:22002/api/latest"
names = ["Detector", "Theta"]

[rbs.hardware.motrona_charge]
type = "motrona_dx350"
title = "Motrona Charge"
url = "http://127.0.0.1:22100/api/latest"

[rbs.hardware.caen]
type = "caen"
title = "Caen"
url = "http://169.254.80.218:22200/api/latest"
detectors = [
	{"board"="10664", "channel"=0, "identifier"="d01", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="10664", "channel"=1, "identifier"="d02", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="33", "channel"=0, "identifier"="MD01", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="33", "channel"=3, "identifier"="MD04", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
]

[erd.hardware.mdrive_z]
type = "mdrive"
title = "MDrive Z"
url = "http://127.0.0.1:22124/api/latest"

[erd.hardware.mdrive_theta]
type = "mdrive"
title = "MDrive Theta"
url = "http://127.0.0.1:22123/api/latest"

[erd.hardware.mpa3]
type = "mpa3"
title = "MPA 3"
url = "http://169.254.155.94:25000/api/latest"

[rbs]
local_dir = "/mnt/mcaiba_nas/transfer_RBS"
remote_dir = "/mnt/winbe_wasp/transfer_RBS"

[erd]
local_dir = "/mnt/mcaiba_nas/transfer_ERD"
remote_dir = "/mnt/winbe_wasp/transfer_ERD"

